name: window_to_front
description: A Flutter plugin to bring a window into focus.
version: 0.0.1
author: Dillon Nys
homepage: https://github.com/dnys1/window_to_front

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      macos:
        pluginClass: WindowToFrontPlugin
